name: App Deploy to AWS

on:
  push:
    branches: [main]

env:
  MAIL_HOST: ${{secrets.MAIL_HOST}}
  MAIL_PORT: ${{secrets.MAIL_PORT}}
  MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
  MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
  MAIL_PROTOCOL: ${{secrets.MAIL_PROTOCOL}}
  POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
  POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
  POSTGRES_DB: ${{secrets.POSTGRES_DB}}
  POSTGRES_SSLMODE: ${{secrets.POSTGRES_SSLMODE}}
  POSTGRES_USER: ${{secrets.POSTGRES_USER}}
  POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GET SOURCE CODE
        uses: actions/checkout@v4

      - name: SETUP JAVA
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '23'

      - name: BUILD PROJECT
        run: mvn clean install -DskipTests

      - name: AUTHENTICATE TO DOCKER HUB
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: BUILD DOCKER IMAGE
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/deploy_jira . --no-cache

      - name: PUSH IMAGE TO DOCKERHUB
        run: docker push ${{secrets.DOCKER_USERNAME}}/deploy_jira

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: PULL IMAGE FROM DOCKERHUB
        run: sudo docker pull ${{secrets.DOCKER_USERNAME}}/deploy_jira:latest

      - name: RUN DOCKER CONTAINER
        run: sudo docker run -d -p 8080:8080 --name deploy_jira